version: '3.4'

services:
  registry:
    image: registry.services.alin.be/registry-image:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=5000
        - traefik.frontend.rule=Host:registry.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#    ports:
#      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry

  registry-ui:
    image: registry.services.alin.be/registry-ui-image:v1
    depends_on:
      - registry
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:registry-ui.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
        - traefik.frontend.auth.basic=admin:$$apr1$$gWiqD1WO$$kJ1Im7XyH2pH5V/D/DmcL.
    volumes:
      - ./registry-ui/registries.yml:/app/registries.yml
      #- ./ssl.crt:/app/ssl.crt # https certfile location
      #- ./ssl.key:/app/ssl.key # https keyfile location
    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
      #- MANAGER_ENABLE_HTTPS=true
      #- MANAGER_KEY=/app/ssl.crt
      #- MANAGER_CERTIFICATE=/app/ssl.key

  registry-ui2:
    image: registry.services.alin.be/registry-ui2-image:v1
    depends_on:
      - registry
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:registry-ui2.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry.services.alin.be
      ENV_DOCKER_REGISTRY_PORT: "80"

networks:
  default:
    external:
      name: traefik-net
