version: '3.4'

services:
  registry:
    image: registry:2.6.2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=5000
        - traefik.frontend.rule=Host:registry.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/certs:/certs
      - ./registry/auth:/auth

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:registry-ui.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry.services.alin.be
      ENV_DOCKER_REGISTRY_PORT: "80"

  registry-ui2:
    image: hyper/docker-registry-web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 540M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:registry-ui2.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    environment:
      REGISTRY_URL: http://registry.services.alin.be/v2
      DELETE_IMAGES: "true"

networks:
  default:
    external:
      name: traefik-net
